### ISSUE TITLE
Model license FAQ omits some differences between CodeML and BigScience OpenRAIL-M.

### ISSUE THREAD

**Issue by mswilson** [bigcode-project/bigcode-website#39]
There are more than 4 modifications when comparing the CodeML Open RAIL License v1.0 and the BigScience RAIL License v1.0.

Here's a diff of a plain text formatting of each of these licenses: https://gist.github.com/mswilson/c66d879e6c2f16e1a2c805d29ff8aec8/revisions?diff=unified

Some of the modifications are in the definitions of terms. There's also some new language in Section II that seems to have been added to address a specific enforcement concern.

I think a FAQ entry that highlights some of the most significant differences makes sense. You don't need to explain every de minimis change like "shall mean" -> "means". But I think that saying "There are 4 modifications" is inaccurate, and there may be some material differences that should be highlighted.

**Comment by harm-devries** [comment]
@mswilson thank you for reaching out (and sorry for the late reply!); we are currently working on improving the license and are aware of the issues you raised. If you would like to give your input on how to improve the license, you're most welcome to [join the project](https://www.bigcode-project.org/docs/about/join/) and participate in the discussions.
